version: '3'

services:
  web:
    build: ./docker/nginx/
    ports:
        - 80:80
    volumes:
        - ./src:/var/www/html
        # - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
        - app
  app:
    build: ./docker/php-fpm/
    volumes:
        - ./src:/var/www/html
  db:
    build: ./docker/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
